export const tokens = {
  bg: 'var(--bg)',
  surface1: 'var(--surface-1)',
  surface2: 'var(--surface-2)',
  border: 'var(--border)',
  text: 'var(--text)',
  textMuted: 'var(--text-muted)',
  textDim: 'var(--text-dim)',
  accent: 'var(--accent)',
  accentSoft: 'var(--accent-soft)',
  work: 'var(--work)',
  rest: 'var(--rest)',
  ready: 'var(--ready)',
  complete: 'var(--complete)',
  paused: 'var(--paused)',
  success: 'var(--success)',
  warning: 'var(--warning)',
  danger: 'var(--danger)',
  info: 'var(--info)',
  radiusSm: 'var(--radius-sm)',
  radiusMd: 'var(--radius-md)',
  radiusPill: 'var(--radius-pill)',
} as const;
